api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import *


router_user_task = routers.SimpleRouter()
router_user_task.register('', TaskViewSet, basename='tasks')

router_user_data = routers.SimpleRouter()
router_user_data.register('', UserViewSet, basename='user')


urlpatterns = [
    path('login/', CustomObtainAuthToken.as_view(), name='drf-login'),

    path('tasks/', include(router_user_task.urls)),

    path('user/', include(router_user_data.urls)),
]

app/urls.py
from django.urls import path
from .views import *

app_name = 'app'

urlpatterns = [
    path('', register_or_login_page, name='login-register'),
    path('task-list/', TaskList.as_view(), name='home'),
    path('detail/<int:pk>/', DetailTask.as_view(), name='task-detail'),
    path('statistics/', statistics, name='statistics'),
    path('create/', CreateTask.as_view(), name='create-task'),

    path('set_status/<int:pk>/<str:set_status>', set_status, name='set-status'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include


'''Add admin custom-page'''

admin.site.index_template = 'admin/my_custom_page.html'
admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('app.urls')),
    path('api/', include('api.urls')),
    # path('', include('custom_page.urls')),
]

templates/app/base_site.html
{% extends "admin/base.html" %}

{% block title %}{% if subtitle %}{{ subtitle }} | {% endif %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">{{ site_header|default:_('Django administration') }}</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

templates/app/create_task.html
{% extends 'base.html' %}
{% block content %}
<h1>Create new Task</h1>
    <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

templates/app/home.html
{% extends 'base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="row">
            <div ><h1 class="text-center"> All {{user.first_name}} tasks </h1></div>
        </div>
        <div class="row justify-content-between">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Task text</th>
                  <th scope="col">Deadline date</th>
                </tr>
              </thead>
              <tbody>
                {% for task in tasks %}
                <tr>
                  <th scope="row"><a href="{% url 'app:task-detail' task.id %}">{{ task.name|capfirst }}</a></th>
                  <td>{{ task.full_text|truncatechars:30 }}</td>
                  <td>{{ task.deadline_date }}</td>
                </tr>
                {% endfor %}

              <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li>
                    <span><a href="?page={{ page_obj.previous_page_number }}">Previous</a></span>
                    </li>
                {% endif %}
                    <li class="">
                        <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                    </li>
                {% if page_obj.has_next %}
                    <li>
                    <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
                    </li>
                {% endif %}
            </ul>


              </tbody>
            </table>

        </div>

    {% else %}
        <div class="row text-center">
            <h1>Please <a href="{% url 'login' %}"> login </a> or <a href="{% url 'register' %}"> register </a></h1>
        </div>
    {% endif %}


{% endblock %}

templates/app/my_custom_page.html
{% extends "admin/base_site.html" %}
{% load i18n static %}
{% block content %}
{% if user.is_superuser  %}
    <fieldset class="module">
        <h3>User count: {{ users_count }} </h3>
        <h3>Number of users registered in the last week: {{ last_registered_users }}</h3>
        <h3>Tasks count: {{ tasks_count }}</h3>
        <h3>Tasks with status to do: {{ tasks_status_todo }}</h3>
        <h3>Tasks with status in_progress: {{ tasks_status_in_progress }}</h3>
        <h3>Tasks with status blocked: {{ tasks_status_blocked }}</h3>
        <h3>Tasks with status finished: {{ tasks_status_finished }}</h3>

    </fieldset>

{% else %}
<h4>You must be an Admin to see this page</h4>
{% endif %}
{% endblock %}

templates/app/staistics.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="border-bottom p-3">Statistic of my tasks</h1>
    <div class="row justify-content-center p-2">
        <div class="col-8">
            <h4> All tasks of {{user.first_name}}: {{all_tasks}} </h4>
        </div>
    </div>
    <div class="row justify-content-center p-2">
        <div class="col-8">
            <h3> Number of tasks by status </h3>
        </div>
    </div>
    <div class="row justify-content-between ">
        <div class="col-4">
            <h5> To do: {{status_todo}} </h5>
        </div>
        <div class="col-4">
            <h5> In progress: {{status_in_progress}} </h5>
        </div>
    </div>
    <div class="row justify-content-between ">
        <div class="col-4">
            <h5> Blocked: {{status_blocked}} </h5>
        </div>
        <div class="col-4">
            <h5> Finished: {{status_finished}} </h5>
        </div>
    </div>
    <div class="row justify-content-center p-2">
        <div class="col-12">
            <h4> Average duration of the task:
                {% if statistic %}
                    It is impossible to calculate the statistics, most likely there are no completed tasks.
                {% else %}
                    {{average_duration_of_the_task}}
                {% endif %}
            </h4>
        </div>
    </div>
{% endblock %}

templates/app/task_detail.html
{% extends 'base.html' %}
{% block content %}

    <div class="row">
        {% if task.owner == user %}
        <div class="row text-center p-2 border-bottom">
                    <h4>{{ task.name|capfirst }}</h4>
            </div>
        <div class="col-3 border-end">
            <div class="row">
                <div class="col-10 p-2">
                    <h6> Deadline date: {{ task.deadline_date }}</h6>
                </div>
            </div>
            <div class="row">
                <div class="col-10 p-2">
                    <h6> Status: {{ task.status }}</h6>
                </div>
            </div>
            <div class="row">
                <div class="col-10 p-2">
                    <h6> Priority: {{ task.priority }}</h6>
                </div>
            </div>
            <div class="row">
                <div class="col-10 p-2">
                    <h6> Importance: {{ task.importance }}</h6>
                </div>
            </div>
            <div class="row">
                <div class="col-10 p-2">
                    <a href="{% url 'app:home' %}" class="btn btn-info ">All tasks</a>
                </div>
            </div>
        </div>
        <div class="col-8 text-center">
            <div class="row  p-2">
                <p>{{ task.full_text }}</p>
            </div>
            <div class="row justify-content-between">
                {% if task.status != 'finished' %}
                    {% if task.status != 'todo' %}
                        <div class="col-4">
                            <a href="{% url 'app:set-status' task.id 'todo' %}" class="btn btn-success">To do</a>
                        </div>
                    {% endif %}
                    {% if task.status != 'in_progress' %}
                        <div class="col-4">
                            <a href="{% url 'app:set-status' task.id 'in_progress' %}" class="btn btn-success">In progress</a>
                        </div>
                    {% endif %}
                    {% if task.status != 'blocked' %}
                        <div class="col-4">
                            <a href="{% url 'app:set-status' task.id 'blocked' %}" class="btn btn-success">Blocked</a>
                        </div>
                    {% endif %}
                    <div class="col-4">
                        <a href="{% url 'app:set-status' task.id 'finished' %}" class="btn btn-success">Finished</a>
                    </div>


                {% endif %}
            </div>
        </div>
        {% endif %}
    </div>

{% endblock %}