api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import *


router_user_task = routers.SimpleRouter()
router_user_task.register('', TaskViewSet, basename='tasks')

router_user_data = routers.SimpleRouter()
router_user_data.register('', UserViewSet, basename='user')


urlpatterns = [
    path('login/', CustomObtainAuthToken.as_view(), name='drf-login'),

    path('tasks/', include(router_user_task.urls)),

    path('user/', include(router_user_data.urls)),
]

app/urls.py
from django.urls import path
from .views import *

app_name = 'app'

urlpatterns = [
    path('', register_or_login_page, name='login-register'),
    path('task-list/', TaskList.as_view(), name='home'),
    path('detail/<int:pk>/', DetailTask.as_view(), name='task-detail'),
    path('statistics/', statistics, name='statistics'),
    path('create/', CreateTask.as_view(), name='create-task'),

    path('set_status/<int:pk>/<str:set_status>', set_status, name='set-status'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include


'''Add admin custom-page'''

admin.site.index_template = 'admin/my_custom_page.html'
admin.autodiscover()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('app.urls')),
    path('api/', include('api.urls')),
    # path('', include('custom_page.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'img/to-do.png' %}" type="image/png">
</head>
<body class="bg=light" >
    <div class="container">
        <header class="border-bottom p-3 mb-3">
            <div class="row justify-content-between">
                <div class="col-2">
                    <a href="{% url 'app:home' %}">
                        <img class="img-fluid w-50" src="{% static 'img/logo.png' %}">
                    </a>
                </div>
                <div class="col-3 text-center">
                    {% if user.is_authenticated %}
                        <a href="{% url 'edit-user' user.id %}">
                            {% if user.first_name %}
                                {{user.first_name}} {{user.last_name}}
                            {% else %}
                                User
                            {% endif %}
                        </a> | <a href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a href="{% url 'register' %}">Register</a> |  <a href="{% url 'login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </header>

        <div class="row justify-content-between">
            <div class="col-2">
                <div class="row">
                {% if user.is_authenticated %}
                    <div class="row">
                        <div class="row text-center">
                            <a class="btn btn-success m-5" href="{% url 'app:create-task' %}">Add new task</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="row text-center">
                            <a class="btn btn-secondary m-5" href="{% url 'app:statistics' %}">Statistics</a>
                        </div>
                    </div>
                {% endif %}
                </div>
            </div>
            <div class="col-9">
                <div class="row text-center p-5">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>




        <footer class="text-center text-lg-start   border-top">
            <div class="row justify-content-between">
                <div class="col-2 p-4">
                    <a href="{% url 'app:home' %}">
                        <img class="img-fluid w-50" src="{% static 'img/logo.png' %}">
                    </a>
                </div>
                <div class="col-2 p-4">
                    <div class="row">
                            This project on Gitlab
                    </div>
                    <div class="row text-center" style="width: 4rem;">
                      <a href="https://gitlab.com/ArtemKAV/petprojecttodoapp" class="me-4 text-reset">
                          <img class="img-fluid" src="{% static 'img/github.png' %}">
                      </a>
                    </div>
                </div>
                <div class="col-2 p-4">
                    {% if user.is_authenticated %}
                        <a href="{% url 'edit-user' user.id %}">
                            {% if user.first_name %}
                                {{user.first_name}} {{user.last_name}}
                            {% else %}
                                User
                            {% endif %}
                        </a>
                    {% endif %}
                </div>
            </div>
          <section class="d-flex justify-content-center justify-content-lg-between p-4 m-5">
            <div class="me-5 d-none d-lg-block">
              <span>Get connected with us on social networks:</span>
            </div>
            <div class="row justify-content-lg-between">
                <div class="col-2" style="width: 4rem;">
                  <a href="https://uk-ua.facebook.com/" class="me-4 text-reset">
                      <img class="img-fluid" src="{% static 'img/facebook.png' %}">
                  </a>
                </div>
                <div class="col-1" style="width: 4rem;">
                  <a href="https://www.instagram.com/" class="me-4 text-reset">
                      <img class="img-fluid" src="{% static 'img/instagram.png' %}">
                  </a>
                </div>
                <div class="col-2" style="width: 4rem;">
                  <a href="https://twitter.com/" class="me-4 text-reset">
                      <img class="img-fluid" src="{% static 'img/twitter.png' %}">
                  </a>
                </div>
                <div class="col-2" style="width: 4rem;">
                  <a href="https://www.youtube.com/" class="me-4 text-reset">
                      <img class="img-fluid" src="{% static 'img/youtube.png' %}">
                  </a>
                </div>

            </div>
          </section>
          <div class="row justify-content-center">

          </div>

        </footer>
    </div>

</body>
</html>